name: webapp-office-x365
version: '0.3'
summary: Unofficial Office
description: Unofficial wrapper for Office 365 web apps.

confinement: strict
base: core18

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]

  webapp-office-x365-qml:
    after: [desktop-qt5]
    source: .
    plugin: dump
    stage-packages:
      - qmlscene
      - qml-module-qtquick2
      - qml-module-qtquick-window2
      - qml-module-qtwebengine
      - qml-module-qtquick-dialogs
    organize:
      webapp-office-x365.launcher: bin/webapp-office-x365.launcher

apps:
  word:
    command: webapp-office-x365.launcher "https://www.office.com/launch/word" "Word"
    desktop: snap/gui/word.desktop
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - screen-inhibit-control
      - x11
    environment: &environment
      DISABLE_WAYLAND: 1
  outlook:
    command: webapp-office-x365.launcher "https://outlook.office.com/calendar/view/week#authRedirect=true" "Outlook"
    desktop: snap/gui/outlook.desktop
    plugs: *plugs
    environment: *environment
  excel:
    command: webapp-office-x365.launcher "https://www.office.com/launch/excel" "Excel"
    desktop: snap/gui/excel.desktop
    plugs: *plugs
    environment: *environment
  powerpoint:
    command: webapp-office-x365.launcher "https://www.office.com/launch/powerpoint" "PowerPoint"
    desktop: snap/gui/powerpoint.desktop
    plugs: *plugs
    environment: *environment
  onenote:
    command: webapp-office-x365.launcher "https://www.onenote.com/notebooks" "OneNote"
    desktop: snap/gui/onenote.desktop
    plugs: *plugs
    environment: *environment
  onedrive:
    command: webapp-office-x365.launcher "https://onedrive.live.com/" "OneDrive"
    desktop: snap/gui/onedrive.desktop
    plugs: *plugs
    environment: *environment
